import { z } from 'zod';
export declare const MemoryScopeSchema: z.ZodEnum<["global", "user", "project", "session"]>;
export declare const MemoryTypeSchema: z.ZodEnum<["user", "preference", "project", "task", "episodic", "semantic", "procedural", "decision", "fact", "relationship", "temporary"]>;
export declare const MemoryStatusSchema: z.ZodEnum<["candidate", "active", "confirmed", "superseded", "archived", "deleted"]>;
export declare const MemoryPrivacyLevelSchema: z.ZodEnum<["public", "internal", "confidential", "restricted"]>;
export declare const DecisionActionSchema: z.ZodEnum<["CREATE", "UPDATE", "MERGE", "CONFLICT", "IGNORE", "SUPERSEDE", "ARCHIVE"]>;
export declare const MemorySchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    user_id: z.ZodString;
    scope: z.ZodEnum<["global", "user", "project", "session"]>;
    project_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    type: z.ZodEnum<["user", "preference", "project", "task", "episodic", "semantic", "procedural", "decision", "fact", "relationship", "temporary"]>;
    content: z.ZodString;
    summary: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    entities: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    topics: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    importance: z.ZodDefault<z.ZodNumber>;
    confidence: z.ZodDefault<z.ZodNumber>;
    created_at: z.ZodString;
    updated_at: z.ZodString;
    valid_from: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    valid_to: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    last_accessed_at: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    access_count: z.ZodDefault<z.ZodNumber>;
    source_provider: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    source_session_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    source_message_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    parent_memory_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodDefault<z.ZodEnum<["candidate", "active", "confirmed", "superseded", "archived", "deleted"]>>;
    privacy_level: z.ZodDefault<z.ZodEnum<["public", "internal", "confidential", "restricted"]>>;
    content_hash: z.ZodString;
    embedding_reference: z.ZodOptional<z.ZodAny>;
}, "strip", z.ZodTypeAny, {
    id: string;
    tenant_id: string;
    user_id: string;
    scope: "global" | "user" | "project" | "session";
    type: "user" | "project" | "preference" | "task" | "episodic" | "semantic" | "procedural" | "decision" | "fact" | "relationship" | "temporary";
    content: string;
    status: "candidate" | "active" | "confirmed" | "superseded" | "archived" | "deleted";
    entities: string[];
    topics: string[];
    importance: number;
    confidence: number;
    created_at: string;
    updated_at: string;
    access_count: number;
    privacy_level: "public" | "internal" | "confidential" | "restricted";
    content_hash: string;
    project_id?: string | null | undefined;
    summary?: string | null | undefined;
    valid_from?: string | null | undefined;
    valid_to?: string | null | undefined;
    last_accessed_at?: string | null | undefined;
    source_provider?: string | null | undefined;
    source_session_id?: string | null | undefined;
    source_message_id?: string | null | undefined;
    parent_memory_id?: string | null | undefined;
    embedding_reference?: any;
}, {
    id: string;
    tenant_id: string;
    user_id: string;
    scope: "global" | "user" | "project" | "session";
    type: "user" | "project" | "preference" | "task" | "episodic" | "semantic" | "procedural" | "decision" | "fact" | "relationship" | "temporary";
    content: string;
    created_at: string;
    updated_at: string;
    content_hash: string;
    project_id?: string | null | undefined;
    summary?: string | null | undefined;
    status?: "candidate" | "active" | "confirmed" | "superseded" | "archived" | "deleted" | undefined;
    entities?: string[] | undefined;
    topics?: string[] | undefined;
    importance?: number | undefined;
    confidence?: number | undefined;
    valid_from?: string | null | undefined;
    valid_to?: string | null | undefined;
    last_accessed_at?: string | null | undefined;
    access_count?: number | undefined;
    source_provider?: string | null | undefined;
    source_session_id?: string | null | undefined;
    source_message_id?: string | null | undefined;
    parent_memory_id?: string | null | undefined;
    privacy_level?: "public" | "internal" | "confidential" | "restricted" | undefined;
    embedding_reference?: any;
}>;
export declare const CreateMemoryInputSchema: z.ZodObject<{
    tenant_id: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    user_id: z.ZodString;
    scope: z.ZodDefault<z.ZodOptional<z.ZodEnum<["global", "user", "project", "session"]>>>;
    project_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    type: z.ZodDefault<z.ZodOptional<z.ZodEnum<["user", "preference", "project", "task", "episodic", "semantic", "procedural", "decision", "fact", "relationship", "temporary"]>>>;
    content: z.ZodString;
    summary: z.ZodOptional<z.ZodString>;
    entities: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    topics: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    importance: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    confidence: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    valid_from: z.ZodOptional<z.ZodString>;
    valid_to: z.ZodOptional<z.ZodString>;
    source_provider: z.ZodOptional<z.ZodString>;
    source_session_id: z.ZodOptional<z.ZodString>;
    source_message_id: z.ZodOptional<z.ZodString>;
    privacy_level: z.ZodDefault<z.ZodOptional<z.ZodEnum<["public", "internal", "confidential", "restricted"]>>>;
}, "strip", z.ZodTypeAny, {
    tenant_id: string;
    user_id: string;
    scope: "global" | "user" | "project" | "session";
    type: "user" | "project" | "preference" | "task" | "episodic" | "semantic" | "procedural" | "decision" | "fact" | "relationship" | "temporary";
    content: string;
    entities: string[];
    topics: string[];
    importance: number;
    confidence: number;
    privacy_level: "public" | "internal" | "confidential" | "restricted";
    project_id?: string | null | undefined;
    summary?: string | undefined;
    valid_from?: string | undefined;
    valid_to?: string | undefined;
    source_provider?: string | undefined;
    source_session_id?: string | undefined;
    source_message_id?: string | undefined;
}, {
    user_id: string;
    content: string;
    tenant_id?: string | undefined;
    scope?: "global" | "user" | "project" | "session" | undefined;
    project_id?: string | null | undefined;
    type?: "user" | "project" | "preference" | "task" | "episodic" | "semantic" | "procedural" | "decision" | "fact" | "relationship" | "temporary" | undefined;
    summary?: string | undefined;
    entities?: string[] | undefined;
    topics?: string[] | undefined;
    importance?: number | undefined;
    confidence?: number | undefined;
    valid_from?: string | undefined;
    valid_to?: string | undefined;
    source_provider?: string | undefined;
    source_session_id?: string | undefined;
    source_message_id?: string | undefined;
    privacy_level?: "public" | "internal" | "confidential" | "restricted" | undefined;
}>;
export declare const UpdateMemoryInputSchema: z.ZodObject<{
    content: z.ZodOptional<z.ZodString>;
    summary: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<["user", "preference", "project", "task", "episodic", "semantic", "procedural", "decision", "fact", "relationship", "temporary"]>>;
    status: z.ZodOptional<z.ZodEnum<["candidate", "active", "confirmed", "superseded", "archived", "deleted"]>>;
    importance: z.ZodOptional<z.ZodNumber>;
    confidence: z.ZodOptional<z.ZodNumber>;
    entities: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    topics: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    valid_from: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    valid_to: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    privacy_level: z.ZodOptional<z.ZodEnum<["public", "internal", "confidential", "restricted"]>>;
}, "strip", z.ZodTypeAny, {
    type?: "user" | "project" | "preference" | "task" | "episodic" | "semantic" | "procedural" | "decision" | "fact" | "relationship" | "temporary" | undefined;
    content?: string | undefined;
    summary?: string | undefined;
    status?: "candidate" | "active" | "confirmed" | "superseded" | "archived" | "deleted" | undefined;
    entities?: string[] | undefined;
    topics?: string[] | undefined;
    importance?: number | undefined;
    confidence?: number | undefined;
    valid_from?: string | null | undefined;
    valid_to?: string | null | undefined;
    privacy_level?: "public" | "internal" | "confidential" | "restricted" | undefined;
}, {
    type?: "user" | "project" | "preference" | "task" | "episodic" | "semantic" | "procedural" | "decision" | "fact" | "relationship" | "temporary" | undefined;
    content?: string | undefined;
    summary?: string | undefined;
    status?: "candidate" | "active" | "confirmed" | "superseded" | "archived" | "deleted" | undefined;
    entities?: string[] | undefined;
    topics?: string[] | undefined;
    importance?: number | undefined;
    confidence?: number | undefined;
    valid_from?: string | null | undefined;
    valid_to?: string | null | undefined;
    privacy_level?: "public" | "internal" | "confidential" | "restricted" | undefined;
}>;
export declare const RecallRequestSchema: z.ZodObject<{
    tenant_id: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    user_id: z.ZodString;
    query: z.ZodString;
    project_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    scope: z.ZodOptional<z.ZodUnion<[z.ZodEnum<["global", "user", "project", "session"]>, z.ZodArray<z.ZodEnum<["global", "user", "project", "session"]>, "many">]>>;
    maxTokens: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    minScore: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    types: z.ZodOptional<z.ZodArray<z.ZodEnum<["user", "preference", "project", "task", "episodic", "semantic", "procedural", "decision", "fact", "relationship", "temporary"]>, "many">>;
    includeSuperseded: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
    temporalDate: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    tenant_id: string;
    user_id: string;
    query: string;
    maxTokens: number;
    minScore: number;
    includeSuperseded: boolean;
    scope?: "global" | "user" | "project" | "session" | ("global" | "user" | "project" | "session")[] | undefined;
    project_id?: string | null | undefined;
    types?: ("user" | "project" | "preference" | "task" | "episodic" | "semantic" | "procedural" | "decision" | "fact" | "relationship" | "temporary")[] | undefined;
    temporalDate?: string | undefined;
}, {
    user_id: string;
    query: string;
    tenant_id?: string | undefined;
    scope?: "global" | "user" | "project" | "session" | ("global" | "user" | "project" | "session")[] | undefined;
    project_id?: string | null | undefined;
    maxTokens?: number | undefined;
    minScore?: number | undefined;
    types?: ("user" | "project" | "preference" | "task" | "episodic" | "semantic" | "procedural" | "decision" | "fact" | "relationship" | "temporary")[] | undefined;
    includeSuperseded?: boolean | undefined;
    temporalDate?: string | undefined;
}>;
export declare const SearchQuerySchema: z.ZodObject<{
    tenant_id: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    user_id: z.ZodOptional<z.ZodString>;
    project_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    query: z.ZodString;
    scope: z.ZodOptional<z.ZodEnum<["global", "user", "project", "session"]>>;
    type: z.ZodOptional<z.ZodEnum<["user", "preference", "project", "task", "episodic", "semantic", "procedural", "decision", "fact", "relationship", "temporary"]>>;
    status: z.ZodOptional<z.ZodEnum<["candidate", "active", "confirmed", "superseded", "archived", "deleted"]>>;
    limit: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    offset: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    valid_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    tenant_id: string;
    query: string;
    limit: number;
    offset: number;
    user_id?: string | undefined;
    scope?: "global" | "user" | "project" | "session" | undefined;
    project_id?: string | null | undefined;
    type?: "user" | "project" | "preference" | "task" | "episodic" | "semantic" | "procedural" | "decision" | "fact" | "relationship" | "temporary" | undefined;
    status?: "candidate" | "active" | "confirmed" | "superseded" | "archived" | "deleted" | undefined;
    valid_at?: string | undefined;
}, {
    query: string;
    tenant_id?: string | undefined;
    user_id?: string | undefined;
    scope?: "global" | "user" | "project" | "session" | undefined;
    project_id?: string | null | undefined;
    type?: "user" | "project" | "preference" | "task" | "episodic" | "semantic" | "procedural" | "decision" | "fact" | "relationship" | "temporary" | undefined;
    status?: "candidate" | "active" | "confirmed" | "superseded" | "archived" | "deleted" | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    valid_at?: string | undefined;
}>;
export declare const MemoryPackManifestSchema: z.ZodObject<{
    schema_version: z.ZodString;
    created_at: z.ZodString;
    exported_by: z.ZodString;
    tenant_id: z.ZodString;
    user_id: z.ZodString;
    project_id: z.ZodNullable<z.ZodString>;
    memory_count: z.ZodNumber;
    relationship_count: z.ZodNumber;
    checksum: z.ZodString;
    format_version: z.ZodLiteral<"1.0.0">;
}, "strip", z.ZodTypeAny, {
    tenant_id: string;
    user_id: string;
    project_id: string | null;
    created_at: string;
    schema_version: string;
    exported_by: string;
    memory_count: number;
    relationship_count: number;
    checksum: string;
    format_version: "1.0.0";
}, {
    tenant_id: string;
    user_id: string;
    project_id: string | null;
    created_at: string;
    schema_version: string;
    exported_by: string;
    memory_count: number;
    relationship_count: number;
    checksum: string;
    format_version: "1.0.0";
}>;
//# sourceMappingURL=schemas.d.ts.map